[package]
name = "twitch-pal-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.16.0"
serde_json = "1.0.78"
rand = "0.8.4"
tokio = { version = "1.15.0", features = ["full"] }